### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by CHBMB** [comment]
I've been using with with no issues @aptalca

**Comment by aptalca** [comment]
That's good to hear.
Feel free to review and merge

**Comment by thelamer** [comment]
Smoke tested locally looks ok , don't forget about triggers .

Any plans to multi arch? Looks like a heavy build , I wonder if we could rip any bins out of the arch Linux packages for arm

**Comment by aptalca** [comment]
Hadn't thought of the arch bins. I just didn't want to bother with building calibre. The author doesn't recommend it and their dependency list gets updated often.

Maybe we can do it later but for now, I just wanted to get it out the door.

**Pull request merged**
