### PR TITLE
Dockerfile: Expose ports.

### PR DESCRIPTION
**Pull request by saltydk**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-calibre/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Would allow service discovery without localhost port bindings.

## Benefits of this PR and context:
Would allow service discovery without localhost port bindings.

## How Has This Been Tested?
This is how I use all other containers.

### CODE REVIEW

**Comment by tobbenb** [comment]
I don't understand what you mean with service discovery?
You will have to expose the port in either your docker run command or in your compose, which the EXPOSE in the dockerfile doesn't have any impact on. 

So what exactly is it that doesn't work without the EXPOSE in the dockerfile?

**Comment by saltydk** [comment]
https://docs.docker.com/engine/reference/builder/#expose when using something like https://hub.docker.com/r/jwilder/nginx-proxy having the EXPOSE utilized means it can automatically identify the ports without having to bind the ports at all. I am not sure if it is a limitation in how this reverse proxy functions but it makes life easier to have the ports exposed and it offers no downside as it doesn't actually open up the ports.

**Comment by tobbenb** [comment]
We have swag, so we don't use other proxys 😉

I didn't know it uses the EXPOSE for this purpose. And it's correct that that adding it to the Dockerfile doesn't open any ports.

You still have to add an entry in the readme-vars.yml

**Review by tobbenb — CHANGES_REQUESTED** [review]
Add entry in the readme-vars.yml file

**Comment by saltydk** [comment]
I'm unsure as to what you're expecting me to add to the readme-vars.yml file. Maybe it is due to it having been a long day. Would appreciate a hint :)

**Comment by tobbenb** [comment]
You need to add the changes in the changelog at the bottom. Newest entry at the top ofrhe changelog list.

**Comment by saltydk** [comment]
Like that? Or you want something more descriptive?

**Comment by tobbenb** [comment]
That is fine.
Could you also remove the second EXPOSE  and move the port after the other port?

EXPOSE 8080 8081

**Comment by Roxedus** [comment]
Just as an FYI, you can also define EXPOSE on runtime. And your choice of proxy can also take ports manually, reading the readme.

**Comment by saltydk** [comment]
I know but from my experience it doesn't work correctly without the expose when I don't do something like a localhost port binding.

**Comment by saltydk** [comment]
I can live with just adding the ports at runtime if the entry bothers you guys.

**Pull request closed without merging**
